print("Hello, World!")
print("Abdul Mannan")
print("Abdul Mannan","Abid")
print(1,2,3)
print("Hello \nWorld")
print("Hello\tWorld")
print("apple","banana","cherry",sep=",")
print(1,2,3,sep="-")
print("Hello",end=" ")
print("world")
print(1,end='')
print(2)
print('He said, "Hello"')
print(r"This is a backslash: \.")
age=23
print("I am ",age," years old")
num=7
print("The square of ",num," is ",num*num)
print("The Number is: " ,7)
for i in range(1,6):
    print(i)